#!/usr/bin/env sh
PATH="${0}"
root="${PATH%/*}"
cp="/bin/cp"  # Default path of `cp`, ensure by: `$ which cp`

# Move the binary to /usr/local/bin, default dehavior
"${cp}" "${root}/bin/washizator" "/usr/local/bin"
